metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  
# Kafka metrics collected using the Kafka protocol
#- module: kafka
#  metricsets:
#    - broker
#    - partition
#    - consumergroup
#    - producer
#    - consumer
#  period: 10s
#  hosts: ["10.155.149.104:9092"]
#  enabled: true

output.elasticsearch:
  hosts: ["http://10.155.149.105:9200"]

setup.kibana:
  host: "http://10.155.149.105:5601"
